/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agripro.frontend;

import agripro.backend.update.UpdateDB;
import agripro.dashboard.main.Main;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JOptionPane;
import ru.krlvm.swingacrylic.SwingAcrylic;

/**
 *
 * @author angera
 */
public class SetPassword extends javax.swing.JFrame {

    /**
     * Creates new form SetPassword
     */
    private String email;

    public SetPassword(String email) {
        this.email = email;
        initComponents();
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Check if the window is maximized
                if ((getExtendedState() & MAXIMIZED_BOTH) == MAXIMIZED_BOTH) {
                    // Set background color of JFrame when maximized
                    getContentPane().setBackground(new Color(153, 153, 153));
                    // Center jPanel1
                    SetPassword.setLocation((getWidth() - SetPassword.getWidth()) / 2,
                            (getHeight() - SetPassword.getHeight()) / 2);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SetPassword = new javax.swing.JPanel();
        PasswordContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PassphraseLabel = new javax.swing.JLabel();
        Passphrase = new javax.swing.JPasswordField();
        PassphraseLabel1 = new javax.swing.JLabel();
        Passphrase1 = new javax.swing.JPasswordField();
        CreatePassBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Password");

        SetPassword.setBackground(new java.awt.Color(153, 153, 153));
        SetPassword.setPreferredSize(new java.awt.Dimension(600, 500));

        PasswordContainer.setBackground(new java.awt.Color(255, 255, 255));
        PasswordContainer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("CREATE PASSWORD");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText("Enter your new password below:");

        PassphraseLabel.setLabelFor(PassphraseLabel);
        PassphraseLabel.setText("Password");

        Passphrase.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N

        PassphraseLabel1.setLabelFor(PassphraseLabel);
        PassphraseLabel1.setText("Confirm Password");

        Passphrase1.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N

        CreatePassBtn.setBackground(new java.awt.Color(0, 102, 102));
        CreatePassBtn.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        CreatePassBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreatePassBtn.setText("Create Password");
        CreatePassBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreatePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatePassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PasswordContainerLayout = new javax.swing.GroupLayout(PasswordContainer);
        PasswordContainer.setLayout(PasswordContainerLayout);
        PasswordContainerLayout.setHorizontalGroup(
            PasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasswordContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(49, 49, 49))
            .addGroup(PasswordContainerLayout.createSequentialGroup()
                .addGroup(PasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PasswordContainerLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(PasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassphraseLabel)
                            .addComponent(Passphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassphraseLabel1)
                            .addComponent(Passphrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PasswordContainerLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(CreatePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PasswordContainerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        PasswordContainerLayout.setVerticalGroup(
            PasswordContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasswordContainerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(PassphraseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passphrase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(PassphraseLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passphrase1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(CreatePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout SetPasswordLayout = new javax.swing.GroupLayout(SetPassword);
        SetPassword.setLayout(SetPasswordLayout);
        SetPasswordLayout.setHorizontalGroup(
            SetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPasswordLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(PasswordContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SetPasswordLayout.setVerticalGroup(
            SetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPasswordLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PasswordContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreatePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatePassBtnActionPerformed
        // TODO add your handling code here:
        var pass = new String(Passphrase.getPassword());  // Get the new password
        var pass1 = new String(Passphrase1.getPassword()); // Get the confirmation password

        // Check if both passwords match
        if (!pass.equals(pass1)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update the password in the database
       int isUpdated = UpdateDB.updateUserPassword(email, pass); // Assuming email is available in scope

       if (isUpdated != -1) {
           JOptionPane.showMessageDialog(this, "Password updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
           SwingAcrylic.prepareSwing();
           Main frame = new Main(email);
           this.dispose();
           frame.setVisible(true);
           SwingAcrylic.processFrame(frame);
           
       } else {
           JOptionPane.showMessageDialog(this, "Failed to update password!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CreatePassBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePassBtn;
    private javax.swing.JPasswordField Passphrase;
    private javax.swing.JPasswordField Passphrase1;
    private javax.swing.JLabel PassphraseLabel;
    private javax.swing.JLabel PassphraseLabel1;
    private javax.swing.JPanel PasswordContainer;
    private javax.swing.JPanel SetPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
