/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package agripro.dashboard.form;

import static agripro.backend.insert.InsertIntoDB.makeApplication;
import agripro.backend.models.User;
import agripro.backend.retrieve.GetUserData;
import javax.swing.SwingUtilities;

/**
 *
 * @author angera
 */
public class ApplySubsidy extends javax.swing.JPanel {

    /**
     * Creates new form ApplySubsidy
     */
    private String email;
    private String idno;
    private String farmerId;
    private String fullname;
    private String subcounty;
    private String serialboards;
    private String location;
    private String address;
    private String subsidyC;
    private String subsidyT;
    private String farmsize = "N/A";
    private String subsidyId;
    private double subsidyPrice;
    private int quantity;
    private String quantityUnit;
    private double totalPrice = 0.0;

    public ApplySubsidy(String Uemail, String farmerId, String subsidyId, String category, String type, String amount) {
        this.subsidyT = type;
        this.email = Uemail;
        this.subsidyC = category;
        this.subsidyId = subsidyId;
        this.subsidyPrice = Double.parseDouble(amount);
        initComponents();
        initUserData();

        if (subsidyC.contains("Fertilizer") || subsidyC.contains("Seeds")) {
            farmsizeTxt.setVisible(true);
            quantityDescription.setText("Quantity(In Kilograms - eg 50)");
            quantityUnit = "Kgs";
            
        } else {
            farmsizeTxt.setVisible(false);
            quantityUnit = "Units";
        }

    }

    private void initUserData() {
        User user = GetUserData.getUserByEmail(email);

        idno = user.getIdNo();
        farmerId = user.getFarmerId();
        fullname = user.getName();
        subcounty = user.getSubcounty();
        location = user.getLocationName();
        address = user.getAddress();

        idnoTxt.setText("ID NO: " + idno);
        fullnameTxt.setText("Full Name: " + fullname);
        subcountyTxt.setText("Sub-county: " + subcounty);
        locationTxt.setText("Location: " + location);
        addressTxt.setText("Physical Address: " + address);
        subsidyAppliedtxt.setText("Subsidy Applied: "+ subsidyC+":- " + subsidyT);

        // Populate numberOfPackets (or numberOfBagsTxt) combobox with values from 0 to 200
        quantityTxt.removeAllItems(); // Clear any existing items first
        for (int i = 0; i <= 500; i++) {
            quantityTxt.addItem(String.valueOf(i)); // Add each number as a String

        }
        // Add action listeners to update amount billed on change
        quantityTxt.addActionListener(e -> calculatePrice());

    }

    private void calculatePrice() {
        quantity = Integer.parseInt((String) quantityTxt.getSelectedItem());

        totalPrice = quantity * subsidyPrice;

        amountBilledTxt.setText(String.valueOf(totalPrice));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelTransparent2 = new agripro.dashboard.swing.PanelTransparent();
        jLabel2 = new javax.swing.JLabel();
        fullnameTxt = new javax.swing.JLabel();
        idnoTxt = new javax.swing.JLabel();
        addressTxt = new javax.swing.JLabel();
        subcountyTxt = new javax.swing.JLabel();
        locationTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JComboBox<>();
        quantityDescription = new javax.swing.JLabel();
        amountBilledTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        farmsizeTxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        subsidyAppliedtxt = new javax.swing.JLabel();
        txtSerialBoard = new javax.swing.JComboBox<>();
        submitBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 700));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FIRST TIME APPLICATION");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(5);
        jLabel1.setPreferredSize(new java.awt.Dimension(900, 30));

        panelTransparent2.setPreferredSize(new java.awt.Dimension(500, 580));

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Personal Information");

        fullnameTxt.setText("Full Name");

        idnoTxt.setText("ID NO");

        addressTxt.setText("Physical Adress");

        subcountyTxt.setText("Sub-County");

        locationTxt.setText("Location");

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel7.setText("Nearest serial board");

        quantityTxt.setBackground(new java.awt.Color(0, 153, 153));
        quantityTxt.setEditable(true);
        quantityTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        quantityTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        quantityDescription.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        quantityDescription.setText("Quantity Apllying For");

        amountBilledTxt.setBackground(new java.awt.Color(0, 153, 153));
        amountBilledTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel9.setText("Amount Billed");

        jLabel4.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jLabel4.setText("Size of the farm");

        farmsizeTxt.setBackground(new java.awt.Color(0, 153, 153));
        farmsizeTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/4 acre", "1/2 acre", "3/4 acre", "1 acre", "2 acres", "more than 2 acres" }));
        farmsizeTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel3.setText("Application Information");
        jLabel3.setDoubleBuffered(true);

        subsidyAppliedtxt.setText("Subsidy Applied:");

        txtSerialBoard.setBackground(new java.awt.Color(0, 153, 153));
        txtSerialBoard.setEditable(true);
        txtSerialBoard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moi’s Bridge Silos", "Kisumu Branch", "Ntimaru Depot", "Homa Bay Depot", "Muhoroni Depot", "Kendu Bay Depot", "Awendo Depot", "Nyansiango Depot", "Bondo Depot", "Chavakali Depot", "Lodwar Depot", "Turbo Depot", "Kipkaren River Depot", "Mokowe Depot", "Hola Depot", "Kilifi Depot", "Kwale Depot", "Changamwe Depot", "Lunga Lunga (Nairobi) Depot", "Kithimani Depot", "Emali Depot", "Kabarnet Depot", "Marigat Depot", "Ol Kalou Depot", "Marsabit Depot", "Mandera Depot", "Garissa Depot" }));

        javax.swing.GroupLayout panelTransparent2Layout = new javax.swing.GroupLayout(panelTransparent2);
        panelTransparent2.setLayout(panelTransparent2Layout);
        panelTransparent2Layout.setHorizontalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(quantityDescription)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(idnoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(farmsizeTxt, 0, 250, Short.MAX_VALUE)
                    .addComponent(quantityTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amountBilledTxt)
                    .addComponent(locationTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subcountyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subsidyAppliedtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(txtSerialBoard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        panelTransparent2Layout.setVerticalGroup(
            panelTransparent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subcountyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subsidyAppliedtxt)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSerialBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(farmsizeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quantityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantityTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountBilledTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        submitBtn.setBackground(new java.awt.Color(51, 153, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransparent2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Close the dialog (popup) after submission
                SwingUtilities.getWindowAncestor(this).dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        serialboards = (String) txtSerialBoard.getSelectedItem();
        var quantitytext = (String) quantityTxt.getSelectedItem() + " " + quantityUnit;
        
        var farmSize = (farmsizeTxt.getSelectedItem() != null) ? (String) farmsizeTxt.getSelectedItem() : "N/A";

        
        
        int serial = makeApplication(farmerId,subsidyId,quantitytext,serialboards,totalPrice, farmSize,"First Time Application");
        
        if(serial != -1){
            // Close the dialog (popup) after submission
                SwingUtilities.getWindowAncestor(this).dispose();
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressTxt;
    private javax.swing.JTextField amountBilledTxt;
    private javax.swing.JComboBox<String> farmsizeTxt;
    private javax.swing.JLabel fullnameTxt;
    private javax.swing.JLabel idnoTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel locationTxt;
    private agripro.dashboard.swing.PanelTransparent panelTransparent2;
    private javax.swing.JLabel quantityDescription;
    private javax.swing.JComboBox<String> quantityTxt;
    private javax.swing.JLabel subcountyTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel subsidyAppliedtxt;
    private javax.swing.JComboBox<String> txtSerialBoard;
    // End of variables declaration//GEN-END:variables
}
